--- #YAML:1.0
name:                   Data-Phrasebook
version:                0.31
abstract:               A collection of modules for accessing phrasebooks from various data sources.
author:
  - Barbie <barbie@cpan.org>

license:                artistic_2
distribution_type:      module
installdirs:            site

requires:
  Module::Pluggable:    2.7
  Test::More:           0.47
recommends:
  Test::More:           0.70
  Test::Pod:            1.00
  Test::Pod::Coverage:  0.08
  Test::CPAN::Meta:     0.13
  Test::CPAN::Meta:     0.08
build_requires:
  Test::More:           0.47

provides:
  Data::Phrasebook:
    file: lib/Data/Phrasebook.pm
    version: 0.31
  Data::Phrasebook::Debug:
    file: lib/Data/Phrasebook/Debug.pm
    version: 0.31
  Data::Phrasebook::Generic:
    file: lib/Data/Phrasebook/Generic.pm
    version: 0.31
  Data::Phrasebook::Loader:
    file: lib/Data/Phrasebook/Loader.pm
    version: 0.31
  Data::Phrasebook::Loader::Base:
    file: lib/Data/Phrasebook/Loader/Base.pm
    version: 0.31
  Data::Phrasebook::Loader::Text:
    file: lib/Data/Phrasebook/Loader/Text.pm
    version: 0.31
  Data::Phrasebook::Plain:
    file: lib/Data/Phrasebook/Plain.pm
    version: 0.31
  Data::Phrasebook::SQL:
    file: lib/Data/Phrasebook/SQL.pm
    version: 0.31
  Data::Phrasebook::SQL::Query:
    file: lib/Data/Phrasebook/SQL/Query.pm
    version: 0.31
no_index:
  directory:
    - t
    - examples

meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Hand 1.0
